### ISSUE TITLE
Restructure cluster_settings

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/shipyard#582]
Currently, `cluster_settings` is a shell script which defines global variables. While it's simple and effective, it's not very friendly and often quite repetitive. Furthermore, some options are defined in a global file and are implicit (i.e. broker is always on the first cluster in the list).

For example, in Shipyard we use the following:
```bash
clusters=('cluster1' 'cluster2')
cluster_nodes['cluster1']="control-plane worker"
cluster_nodes['cluster2']="control-plane worker"

cluster_cni=( ['cluster1']="weave" ['cluster2']="weave" )

cluster_subm=( ['cluster1']="true" ['cluster2']="true" )
```

I propose we instead define it in YAML with ability to specify defaults, e.g.
```yaml
cni: weave
nodes: control-plane worker
clusters:
  cluster1:
  cluster2:
```

For more advanced uses, this syntax allows greater readability, e.g. to define 3 clusters with ovn on one of them and broker on cluster1:
```yaml
cni: weave
submariner: false
nodes: control-plane worker
clusters:
  cluster1:
    broker: true
    nodes: control-plane
  cluster2:
    submariner: true
  cluster3:
    submariner: true
    cni: ovn
```
